from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import psycopg2

from ship_compliance.ci.gates import ExitCode, GateResult

DEFAULT_OUTPUT = Path("ship-compliance/artifacts/fedramp-oscal.json")


def _base_oscal_document() -> dict[str, Any]:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    return {
        "assessment-results": {
            "uuid": "ship-compliance-template",
            "metadata": {
                "title": "Ship FedRAMP Assessment Results (Template)",
                "last-modified": now,
                "version": "0.1.0",
                "oscal-version": "1.1.2",
            },
            "import-ap": {
                "href": "https://example.invalid/fedramp/system-security-plan.json",
            },
            "results": [
                {
                    "uuid": "result-template",
                    "title": "Automated compliance extraction",
                    "description": "Initial template generated by ship-compliance export fedramp.",
                    "start": now,
                    "end": now,
                    "findings": [],
                }
            ],
        }
    }


def _fetch_document_evidence() -> tuple[list[dict[str, Any]], list[str]]:
    warnings: list[str] = []
    dsn = os.getenv("DATABASE_URL")
    if not dsn:
        warnings.append("DATABASE_URL not set; exporter used template-only output.")
        return [], warnings

    rows: list[dict[str, Any]] = []
    try:
        connection = psycopg2.connect(dsn, connect_timeout=5)
        connection.set_session(readonly=True, autocommit=True)
        with connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT id::text, title::text
                FROM documents
                ORDER BY id DESC
                LIMIT 25
                """
            )
            for row in cursor.fetchall():
                rows.append(
                    {
                        "id": row[0],
                        "title": row[1],
                    }
                )
        connection.close()
    except Exception as exc:
        warnings.append(f"Database evidence query failed: {exc}")

    return rows, warnings


def export_fedramp_oscal(
    repo_root: Path,
    output_path: Path | None = None,
    *,
    strict: bool = False,
) -> tuple[GateResult, dict[str, Any], Path]:
    output = output_path or (repo_root / DEFAULT_OUTPUT)
    if not output.is_absolute():
        output = repo_root / output

    document = _base_oscal_document()
    evidence_rows, warnings = _fetch_document_evidence()

    findings = document["assessment-results"]["results"][0]["findings"]
    for evidence in evidence_rows:
        findings.append(
            {
                "uuid": f"document-{evidence['id']}",
                "title": f"Document Evidence: {evidence['title']}",
                "description": "Evidence discovered from documents table.",
                "target": {"description": "AC-2 account management evidence placeholder"},
            }
        )

    if warnings:
        document["warnings"] = warnings

    try:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(json.dumps(document, indent=2), encoding="utf-8")
    except Exception as exc:
        return (
            GateResult(
                name="export-fedramp",
                exit_code=ExitCode.ERROR,
                message="Failed to write OSCAL JSON output.",
                data={"error": str(exc), "path": str(output)},
            ),
            document,
            output,
        )

    if warnings and strict:
        return (
            GateResult(
                name="export-fedramp",
                exit_code=ExitCode.ERROR,
                message="OSCAL export completed with warnings under --strict mode.",
                data={"warnings": warnings, "path": str(output)},
            ),
            document,
            output,
        )

    message = "FedRAMP OSCAL JSON exported."
    if warnings:
        message = "FedRAMP OSCAL JSON exported with warnings."
    return (
        GateResult(
            name="export-fedramp",
            exit_code=ExitCode.PASS,
            message=message,
            data={"warnings": warnings, "path": str(output)},
        ),
        document,
        output,
    )
